### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by veselychess** [Zerbinati/S_XPrO-NN#1]
when i compile all your sources i got same error missing curl/curl.h

g++ -march=native -Wall -Wcast-qual -std=c++11  -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -Wall -Wcast-qual -std=c++11  -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -Wall -Wcast-qual -std=c++11 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT   -c -o uci.o uci.cpp
search.cpp:44:10: fatal error: curl/curl.h: No such file or directory
   44 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

when i compile stockmaster-master everyhing is ok, 
i use mingw64

**Comment by veselychess** [comment]
ok i install curl library and still has errors, can u help me how u compile your source?

**Comment by Zerbinati** [comment]
you have to copy to the subfolders of MinGW 32\64

32
the curl folder to:
i686-w64-mingw32\include\
file libcurl.a to:
i686-w64-mingw32\lib

64
the curl folder to:
x86_w64-mingw32\include
file libcurl.a to:
x86_w64-mingw32\lib
https://www.mediafire.com/file/b2x54mx2ikb8l8k/curl.7z/file

Regards
M.Z

Il giorno sab 1 feb 2020 alle ore 02:16 veselychess <
notifications@github.com> ha scritto:
